const nodes=['CORPORATE','ORIGINATION','STRUCTURING','DISTRIBUTION','LIQUIDITY'];
const frictions=[['01','ACCESS','Capital demand and investment liquidity rarely meet in one continuous flow.'],['02','PRICING','Fragmented execution makes pricing less transparent and capital less efficient.'],['03','LIQUIDITY','A transaction can create an asset without creating a reliable path for secondary liquidity.'],['04','REUSE','Capital often stops at settlement instead of becoming the input for the next transaction.']];
const oldModel=['Product','Transaction','Settlement'];
const jasmine=['Capital','Origination','Structuring','Distribution','Liquidity','Reuse','Repeat'];
function Flow(){return <div className="flow-stage" aria-label="Capital flow"><div className="flow-line"/>{nodes.map((n,i)=><div className="flow-node" key={n} style={{left:(8+i*21)+'%'}}><span>{n}</span></div>)}</div>}
function Section({id,eyebrow,title,children,copy}:{id:string;eyebrow:string;title:string;children:React.ReactNode;copy:string}){return <section id={id} className="section"><div className="section-head"><div className="eyebrow">{eyebrow}</div><div><h2>{title}</h2><p>{copy}</p></div></div>{children}</section>}
export default function Home(){return <main className="page"><nav className="mono" style={{position:'fixed',zIndex:10,top:0,left:0,right:0,padding:'22px 32px',display:'flex',justifyContent:'space-between',fontSize:11,letterSpacing:'.12em',background:'linear-gradient(var(--bg),transparent)'}}><a href="#">JASMINE</a><span>CAPITAL DISTRIBUTION / LIQUIDITY</span></nav>
<section className="section hero"><div><div className="eyebrow reveal">JASMINE / 02.0</div><h1 className="reveal delay1">CAPITAL<br/>DISTRIBUTION<br/><span style={{color:'var(--accent)'}}>&amp; LIQUIDITY</span><br/>ENGINE</h1></div><div><div className="hero-sub reveal delay2"><div className="eyebrow">THE THESIS</div><p className="hero-copy">Connecting corporate capital demand with investor liquidity — through origination, structuring, distribution, secondary markets and capital reuse.</p></div><Flow/></div></section>
<Section id="capital" eyebrow="01 / CAPITAL IS THERE" title="Capital exists. Liquidity is fragmented." copy="The opportunity is not to create another instrument. It is to connect capital demand and investment liquidity into a repeatable financial flow."><div className="capital-grid"><div className="capital-cell"><span className="eyebrow">DEMAND</span><strong>Corporate<br/>Capital</strong><p>Financing needs across working capital, assets, projects and structured flows.</p></div><div className="capital-cell capital-center"><div className="capital-ring">CAPITAL<br/>ROUTING</div></div><div className="capital-cell"><span className="eyebrow">SUPPLY</span><strong>Investor<br/>Liquidity</strong><p>Capital looking for yield, diversification, liquidity and efficient deployment.</p></div></div></Section>
<Section id="friction" eyebrow="02 / THE FRICTION" title="The gap is not the absence of capital." copy="It is the friction between access, pricing, liquidity and reuse. Jasmine is designed around removing those frictions where the economics justify it."><div className="frictions">{frictions.map(([n,h,p])=><article className="friction" key={n}><b>{n}</b><h3>{h}</h3><p>{p}</p></article>)}</div></Section>
<Section id="thesis" eyebrow="03 / JASMINE THESIS" title="From financial instruments to capital infrastructure." copy="CFA is not the destination. It is one of the instruments inside the engine — used where it improves speed, access, automation, settlement, distribution or capital efficiency."><div className="thesis"><div className="model"><h3>Existing model</h3><div className="steps">{oldModel.map((x,i)=><div className="step" key={x}><i>0{i+1}</i>{x}</div>)}</div></div><div className="model jasmine"><h3>Jasmine model</h3><div className="steps">{jasmine.map((x,i)=><div className="step" key={x}><i>{String(i+1).padStart(2,'0')}</i>{x}</div>)}</div></div></div></Section>
<footer className="footer"><span>JASMINE / CAPITAL DISTRIBUTION &amp; LIQUIDITY ENGINE</span><span>VERTICAL SLICE 01</span></footer></main>}
