'use client';

import { Fragment, useEffect, useState } from 'react';

const nodes=['КОРПОРАТИВНЫЙ','ОРИГИНАЦИЯ','СТРУКТУРИРОВАНИЕ','ДИСТРИБУЦИЯ','ЛИКВИДНОСТЬ'];
const frictions=[['01','ДОСТУП','Спрос на капитал и инвестиционная ликвидность редко соединяются в одном непрерывном потоке.'],['02','ЦЕНООБРАЗОВАНИЕ','Фрагментированное исполнение снижает прозрачность ценообразования и эффективность использования капитала.'],['03','ЛИКВИДНОСТЬ','Транзакция может создать актив, не создавая надёжного механизма вторичной ликвидности.'],['04','ПОВТОРНОЕ ИСПОЛЬЗОВАНИЕ','Капитал часто останавливается на расчётах вместо того, чтобы становиться ресурсом для следующей транзакции.']];
const oldModel=['Продукт','Транзакция','Расчёты'];
const jasmine=['Капитал','Оригинация','Структурирование','Дистрибуция','Ликвидность','Повторное использование','Повторение'];
function Flow(){const [active,setActive]=useState(0);useEffect(()=>{const id=setInterval(()=>setActive(x=>(x+1)%nodes.length),1200);return()=>clearInterval(id)},[]);return <div className="flow-stage" aria-label="Движение капитала"><div className="flow-line"/>{nodes.map((n,i)=><div className={'flow-node '+(i===active?'active':'')} key={n} style={{left:(8+i*21)+'%'}}><span>{n}</span></div>)}</div>}
function Section({id,eyebrow,title,children,copy}:{id:string;eyebrow:string;title:string;children:React.ReactNode;copy:string}){return <section id={id} className="section"><div className="section-head"><div className="eyebrow">{eyebrow}</div><div><h2>{title}</h2><p>{copy}</p></div></div>{children}</section>}

const engineScenarios = {
  Financing:{label:'КОРПОРАТИВНОЕ ФИНАНСИРОВАНИЕ',type:'СТОК',desc:'Долгосрочный спрос на капитал, где важны структура, соответствие инвестору и повторяемость выпусков.',cfa:'Целесообразен, когда структурированный выпуск, расчёты и дистрибуция улучшают доступ к финансированию или снижают операционные затраты.',investor:'ЧАСТНЫЕ / ИНСТИТУЦИОНАЛЬНЫЕ',liquidity:'ПЕРВИЧНЫЙ → ВЫБОРОЧНЫЙ ВТОРИЧНЫЙ',reuse:'РЕИНВЕСТИРОВАНИЕ / РЕФИНАНСИРОВАНИЕ',value:'ОРИГИНАЦИЯ + СТРУКТУРИРОВАНИЕ + ДИСТРИБУЦИЯ'},
  Structured:{label:'СТРУКТУРИРОВАННЫЙ ПОТОК',type:'ГИБРИД',desc:'Потоки с обеспечением или коммерческие потоки, где взаимосвязаны финансирование, дистрибуция и распределение риска.',cfa:'Целесообразен, когда программируемость, прозрачность и автоматизированное обслуживание улучшают структуру.',investor:'ИНСТИТУЦИОНАЛЬНЫЕ / КОРПОРАТИВНЫЕ',liquidity:'ПЕРВИЧНЫЙ + ВТОРИЧНЫЙ',reuse:'ТОРГОВЛЯ / ФИНАНСИРОВАНИЕ / ПОВТОРНОЕ ИСПОЛЬЗОВАНИЕ',value:'СТРУКТУРИРОВАНИЕ + ДИСТРИБУЦИЯ + ФИНАНСИРОВАНИЕ'},
  Treasury:{label:'ЛИКВИДНОСТЬ И КАЗНАЧЕЙСТВО',type:'ПОТОК',desc:'Краткосрочные потребности в капитале, где скорость, расчёты и повторяемость могут существенно изменить экономику.',cfa:'Целесообразен только там, где автоматизация, расчёты или контролируемая передача создают измеримую эффективность.',investor:'ПОСТАВЩИКИ ЛИКВИДНОСТИ / ИНВЕСТОРЫ',liquidity:'МНОГОКРАТНО ИСПОЛЬЗУЕМЫЙ / ВЫСОКАЯ ЧАСТОТА',reuse:'КАПИТАЛ → СЛЕДУЮЩИЙ ПОТОК',value:'ДИСТРИБУЦИЯ + ФИНАНСИРОВАНИЕ + ИНФРАСТРУКТУРА'}
} as const;
const engineStages = ['СПРОС НА КАПИТАЛ','ОРИГИНАЦИЯ','СТРУКТУРИРОВАНИЕ','ДИСТРИБУЦИЯ','ПЕРВИЧНЫЙ РЫНОК','ВТОРИЧНЫЙ РЫНОК','ПОВТОРНОЕ ИСПОЛЬЗОВАНИЕ','CONTRIBUTION P&L'];
function JasmineEngine(){
  const [scenario,setScenario]=useState<keyof typeof engineScenarios>('Financing');
  const [stage,setStage]=useState(0); const s=engineScenarios[scenario];
  const stageCopy=[
    ['ПОЧЕМУ СЕЙЧАС',s.desc],
    ['ИСТОЧНИК','Направить квалифицированный '+s.label.toLowerCase()+' в повторяемый поток капитала.'],
    ['КОНСТРУКЦИЯ','Выбирать структуру, распределение риска и инструмент только там, где они улучшают экономику базовой операции.'],
    ['СОПОСТАВЛЕНИЕ','Соединить структуру с сегментом инвесторов, наиболее соответствующим её профилю риска, доходности и ликвидности.'],
    ['ВЫПУСК','Создать первичную транзакцию и сформировать путь к следующему движению капитала.'],
    ['ЛИКВИДНОСТЬ','Обеспечить ценообразование, передачу и вторичное исполнение там, где это оправдано спросом и экономикой.'],
    ['ПОВТОРНОЕ ИСПОЛЬЗОВАНИЕ','Вернуть капитал в финансирование, обеспечение, реинвестирование или следующий выпуск.'],
    ['ЦЕННОСТЬ','Целевой результат — '+s.value.toLowerCase()+' за вычетом переменных затрат и затрат на риск.']
  ][stage];
  return <Section id="engine" eyebrow="03.5 / КОНТУР JASMINE" title="Один поток. Один экономический тест." copy="Выберите сценарий использования капитала. Затем пройдите один и тот же контур от спроса до contribution P&L. Инструмент меняется — операционная логика остаётся.">
    <div className="engine-shell">
      <div className="engine-scenarios">{(Object.keys(engineScenarios) as Array<keyof typeof engineScenarios>).map(x=><button className={scenario===x?'selected':''} onClick={()=>{setScenario(x);setStage(0)}} key={x}><span>{engineScenarios[x].type}</span>{engineScenarios[x].label}</button>)}</div>
      <div className="engine-route">{engineStages.map((x,i)=><Fragment key={x}><button className={stage===i?'active':''} onClick={()=>setStage(i)}><i>{String(i+1).padStart(2,'0')}</i><span>{x}</span></button>{i<engineStages.length-1&&<b>→</b>}</Fragment>)}</div>
      <div className="engine-detail"><div><span className="eyebrow">{stageCopy[0]}</span><h3>{stageCopy[1]}</h3><p>{s.desc}</p></div><div className="engine-metrics"><div><span className="eyebrow">ТИП КАПИТАЛА</span><strong>{s.type}</strong></div><div><span className="eyebrow">ИНВЕСТОР</span><strong>{s.investor}</strong></div><div><span className="eyebrow">ЛИКВИДНОСТЬ</span><strong>{s.liquidity}</strong></div><div><span className="eyebrow">ПОВТОРНОЕ ИСПОЛЬЗОВАНИЕ</span><strong>{s.reuse}</strong></div></div></div>
      <div className="engine-bottom"><div><span className="eyebrow">ТЕСТ ЦФА</span><strong>{s.cfa}</strong></div><div><span className="eyebrow">ЭКОНОМИЧЕСКИЙ ПУЛ ЦЕННОСТИ</span><strong>{s.value}</strong></div></div>
    </div>
  </Section>
}
const liquidityModes = {
  Primary:{label:'ПЕРВИЧНЫЙ РЫНОК',desc:'Капитал движется от эмитента к первому инвестору. Контур сфокусирован на оригинации, структурировании и дистрибуции.',route:['ЭМИТЕНТ','СТРУКТУРА','ИНВЕСТОР A'],signals:['ОРИГИНАЦИЯ','СТРУКТУРИРОВАНИЕ','ДИСТРИБУЦИЯ']},
  Secondary:{label:'ВТОРИЧНЫЙ РЫНОК',desc:'Капитал движется между инвесторами. Контур сфокусирован на ценообразовании, маркет-мейкинге и ликвидности.',route:['ИНВЕСТОР A','ВТОРИЧНЫЙ РЫНОК','ИНВЕСТОР B'],signals:['ТОРГОВЛЯ','МАРКЕТ-МЕЙКИНГ','ЦЕНООБРАЗОВАНИЕ']}
} as const;
function LiquiditySection(){
  const [mode,setMode]=useState<keyof typeof liquidityModes>('Primary');
  const m=liquidityModes[mode];
  return <Section id="liquidity" eyebrow="03 / КОНТУР ЛИКВИДНОСТИ" title="Транзакция должна создавать путь к следующей транзакции." copy="Первичный выпуск — только начало. Вторичная торговля, маркет-мейкинг, обратная связь по цене и финансирование превращают актив в повторно используемый компонент капитала.">
    <div className="liquidity-map"><div className="liquidity-toolbar"><div className="toggle">{(Object.keys(liquidityModes) as Array<keyof typeof liquidityModes>).map(x=><button className={mode===x?'selected':''} onClick={()=>setMode(x)} key={x}>{x}</button>)}</div><span className="liquidity-status"><span className="pulse"/> {m.label}</span></div>
    <p className="interactive-copy">{m.desc}</p><div className="capital-path"><span>КАПИТАЛ</span><i>→</i><strong>{mode==='Primary'?'ЭМИТЕНТ':'ИНВЕСТОР A'}</strong><i>→</i><b>{mode==='Primary'?'ПЕРВИЧНЫЙ РЫНОК':'ВТОРИЧНЫЙ РЫНОК'}</b><i>→</i><strong>{mode==='Primary'?'ИНВЕСТОР A':'ИНВЕСТОР B'}</strong><i>→</i><span>{mode==='Primary'?'ЛИКВИДНОСТЬ':'ПОВТОРНОЕ ИСПОЛЬЗОВАНИЕ'}</span></div><div className="liq-row">{m.route.map((x,i)=><Fragment key={x}><span className={i===1?'route-core':''}>{x}</span>{i<2&&<b>→</b>}</Fragment>)}</div>
    <div className="liq-secondary"><span>{m.signals[0]}</span><strong>{m.signals[1]}</strong><span>{m.signals[2]}</span></div><div className="liq-footer"><span>ОБРАТНАЯ СВЯЗЬ ПО ЦЕНЕ</span><span>↕ КАПИТАЛ</span><span>ЛИКВИДНОСТЬ</span></div></div>
  </Section>
}
const systemModes = {
  Stock:{title:'Корпоративное финансирование',desc:'Потребности в более долгосрочном финансировании, где важны качество актива, структура и повторяемость выпусков.',examples:['Дебиторская задолженность','Инфраструктура','Реальные активы'],liquidity:'Структурированная / периодическая',economics:'Оригинация + структурирование'},
  Hybrid:{title:'Структурированные потоки',desc:'Структуры, объединяющие базовые активы или коммерческие потоки с финансированием и дистрибуцией.',examples:['Цепочки поставок','С обеспечением','Товарные / складские'],liquidity:'Первичный + выборочный вторичный',economics:'Структурирование + дистрибуция + финансирование'},
  Flow:{title:'Ликвидность и казначейство',desc:'Краткосрочные потребности, где скорость, автоматизация, расчёты и повторное использование могут существенно улучшить экономику.',examples:['Краткосрочное финансирование','Казначейство','Торговые потоки'],liquidity:'Высокая частота / многократное использование',economics:'Дистрибуция + финансирование + инфраструктура'}
} as const;
function BusinessSystemSection(){
  const [mode,setMode]=useState<keyof typeof systemModes>('Stock'); const m=systemModes[mode];
  return <Section id="system" eyebrow="04 / БИЗНЕС-СИСТЕМА" title="Сток. Гибрид. Поток." copy="Карта возможностей — это система сценариев использования капитала, а не каталог продуктов ЦФА. Инструменты используются только там, где они улучшают экономику базовой операции.">
    <div className="system-interactive"><div className="system-tabs">{(Object.keys(systemModes) as Array<keyof typeof systemModes>).map(x=><button className={mode===x?'selected':''} onClick={()=>setMode(x)} key={x}>{x==='Stock'?'Сток':x==='Hybrid'?'Гибрид':'Поток'}</button>)}</div>
    <div className="system-detail"><div><span className="eyebrow">ВЫБРАННЫЙ СЛОЙ</span><h3>{m.title}</h3><p>{m.desc}</p></div><div><span className="eyebrow">СЦЕНАРИИ</span>{m.examples.map(x=><strong key={x}>{x}</strong>)}</div><div><span className="eyebrow">ЛИКВИДНОСТЬ ПРОФИЛЬ</span><strong>{m.liquidity}</strong><span className="eyebrow">ПЕРВИЧНЫЙ РЫНОК ЦЕННОСТЬ ПУЛ</span><strong>{m.economics}</strong></div></div></div>
  </Section>
}
const econPools = {
  ORIGINATION:'Ценность создаётся за счёт привлечения квалифицированного корпоративного спроса и превращения его в повторяемый поток финансирования.',
  STRUCTURING:'Ценность создаётся за счёт структуры, которая улучшает соответствие финансирования, дистрибуцию и распределение риска.',
  DISTRIBUTION:'Ценность создаётся за счёт сопоставления инструментов со спросом инвесторов и снижения трения при размещении.',
  SECONDARY:'Ценность создаётся, когда существующая позиция может сменить владельца благодаря достоверному ценообразованию и исполнению.',
  ФИНАНСИРОВАНИЕ:'Ценность создаётся, когда актив или позиция становится полезным ресурсом для другой финансовой транзакции.',
  ИНФРАСТРУКТУРА:'Ценность создаётся за счёт снижения переменных затрат на повторные выпуски, расчёты, обслуживание и потоки данных.'
} as const;
function EconomicsSection(){
  const [pool,setPool]=useState<keyof typeof econPools>('DISTRIBUTION');
  return <Section id="economics" eyebrow="05 / ЭКОНОМИКА" title="Объём ≠ Ценность." copy="Ключевой показатель для решения — contribution P&amp;L, а не объём выпуска. Каждый поток должен выдерживать переменные затраты, затраты на риск и требования к капиталу.">
    <div className="economics"><div className="econ-formula"><span>ПУЛЫ ВЫРУЧКИ</span><b>−</b><span>ПЕРЕМЕННЫЕ ЗАТРАТЫ</span><b>−</b><span>ЗАТРАТЫ НА РИСК</span><b>=</b><strong>CONTRIBUTION P&amp;L</strong></div>
    <div className="econ-grid">{(Object.keys(econPools) as Array<keyof typeof econPools>).map(x=><button className={pool===x?'selected':''} onClick={()=>setPool(x)} key={x}><span className="eyebrow">{x==='ORIGINATION'?'ОРИГИНАЦИЯ':x==='STRUCTURING'?'СТРУКТУРИРОВАНИЕ':x==='DISTRIBUTION'?'ДИСТРИБУЦИЯ':x==='SECONDARY'?'ВТОРИЧНЫЙ РЫНОК':x==='ФИНАНСИРОВАНИЕ'?'ФИНАНСИРОВАНИЕ':'ИНФРАСТРУКТУРА'}</span><p>{econPools[x]}</p></button>)}</div>
    <div className="econ-readout"><span className="eyebrow">ТЕСТ CONTRIBUTION</span><strong>{pool==='ORIGINATION'?'ОРИГИНАЦИЯ':pool==='STRUCTURING'?'СТРУКТУРИРОВАНИЕ':pool==='DISTRIBUTION'?'ДИСТРИБУЦИЯ':pool==='SECONDARY'?'ВТОРИЧНЫЙ РЫНОК':pool==='ФИНАНСИРОВАНИЕ'?'ФИНАНСИРОВАНИЕ':'ИНФРАСТРУКТУРА'}</strong><p>{econPools[pool]} Тест — остаётся ли contribution положительным после переменных затрат и затрат на риск, а не растёт ли номинальный объём.</p></div></div>
  </Section>
}
export default function Home(){return <main className="page"><nav className="nav mono"><a href="#">JASMINE</a><div className="nav-links"><a href="#capital">01 ПРОБЛЕМА</a><a href="#engine">02 КОНТУР</a><a href="#liquidity">03 ЛИКВИДНОСТЬ</a><a href="#economics">04 ЭКОНОМИКА</a><a href="#vtb">05 ВТБ</a><a href="#roadmap">06 ДОРОЖНАЯ КАРТА</a></div><span className="nav-progress">КАПИТАЛ / МАРШРУТИЗАЦИЯ / ЛИКВИДНОСТЬ</span></nav>
<section className="section hero"><div><div className="eyebrow reveal">JASMINE / 02.0</div><h1 className="reveal delay1">КАПИТАЛ<br/>ДИСТРИБУЦИЯ<br/><span style={{color:'var(--accent)'}}>&amp; ЛИКВИДНОСТЬ</span><br/>КОНТУР</h1></div><div><div className="hero-sub reveal delay2"><div className="eyebrow">ТЕЗИС</div><p className="hero-copy">Соединение корпоративного спроса на капитал с инвестиционной ликвидностью — через оригацию, структурирование, дистрибуцию, вторичный рынок и повторное использование капитала.</p></div><Flow/></div></section>
<Section id="capital" eyebrow="01 / КАПИТАЛ ЕСТЬ" title="Капитал существует. Ликвидность фрагментирована." copy="Возможность не в создании ещё одного инструмента. Она в соединении спроса на капитал и инвестиционной ликвидности в повторяемый финансовый поток."><div className="capital-grid"><div className="capital-cell"><span className="eyebrow">СПРОС</span><strong>Корпоративный<br/>капитал</strong><p>Потребности в финансировании оборотного капитала, активов, проектов и структурированных потоков.</p></div><div className="capital-cell capital-center"><div className="capital-ring">МАРШРУТИЗАЦИЯ<br/>КАПИТАЛА</div></div><div className="capital-cell"><span className="eyebrow">ПРЕДЛОЖЕНИЕ</span><strong>Инвестиционная<br/>ликвидность</strong><p>Капитал, который ищет доходность, диверсификацию, ликвидность и эффективное размещение.</p></div></div></Section>
<Section id="friction" eyebrow="02 / ТРЕНИЕ" title="Разрыв не в отсутствии капитала." copy="Он в трении между доступом, ценообразованием, ликвидностью и повторным использованием. Jasmine устраняет эти барьеры там, где это оправдано экономикой."><div className="frictions">{frictions.map(([n,h,p])=><article className="friction" tabIndex={0} key={n}><b>{n}</b><h3>{h}</h3><p>{p}</p><span className="friction-mark">↗</span></article>)}</div></Section>
<Section id="thesis" eyebrow="03 / ТЕЗИС JASMINE" title="От финансовых инструментов к инфраструктуре капитала." copy="ЦФА — не конечная цель. Это один из инструментов внутри контура — там, где он улучшает скорость, доступ, автоматизацию, расчёты, дистрибуцию или эффективность капитала."><div className="thesis"><div className="model"><h3>Текущая модель</h3><div className="steps">{oldModel.map((x,i)=><div className="step" key={x}><i>0{i+1}</i>{x}</div>)}</div></div><div className="model jasmine"><h3>Модель Jasmine</h3><div className="steps">{jasmine.map((x,i)=><div className="step" key={x}><i>{String(i+1).padStart(2,'0')}</i>{x}</div>)}</div></div></div></Section>
<JasmineEngine/><LiquiditySection/>
<Section id="reuse" eyebrow="03.5 / КАПИТАЛ ПОВТОРНОЕ ИСПОЛЬЗОВАНИЕ" title="Капитал не останавливается на расчётах." copy="Контур усиливается, когда инвестор может торговать, финансировать, реинвестировать и возвращать капитал в следующий выпуск."><div className="reuse-loop">{['Выпуск','Инвестиция','Торговля','Обеспечение','Финансирование','Реинвестирование','Новый выпуск'].map((x,i)=><div className="reuse-node" key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div></Section>
<BusinessSystemSection/>
<EconomicsSection/>
<Section id="vtb" eyebrow="06 / ПОЧЕМУ ВТБ" title="Преимущество не в одном продукте. Оно в комбинации возможностей." copy="У ВТБ уже есть элементы системы: корпоративная оригация, рынки капитала, дистрибуция, ликвидность, инфраструктура и риск. Jasmine соединяет их в повторяемый поток."><div className="vtb-stack"><div><span className="eyebrow">СЕГОДНЯ</span><strong>Корпоративная оригинация</strong><strong>Рынки капитала</strong><strong>Дистрибуция инвесторам</strong><strong>Риск и инфраструктура</strong></div><div className="stack-arrow">→</div><div className="jasmine-core"><span className="eyebrow">JASMINE</span><strong>СОЕДИНИТЬ</strong><p>Направлять спрос к ликвидности. Возвращать ликвидность к спросу.</p></div><div><span className="eyebrow">ФОРМИРУЕТСЯ СО ВРЕМЕНЕМ</span><strong>Ликвидность</strong><strong>Данные о ценообразовании</strong><strong>Повторяемость</strong><strong>Повторное использование капитала</strong></div></div></Section>
<Section id="flywheel" eyebrow="07 / МАХОВИК" title="Ликвидность creates the conditions for more liquidity." copy="Маховик — не утверждение о сетевом эффекте. Каждый шаг должен улучшать экономику следующего шага."><div className="flywheel">{['ЭМИТЕНТЫ','ИНСТРУМЕНТЫ','ИНВЕСТОРЫ','ЛИКВИДНОСТЬ','ЦЕНООБРАЗОВАНИЕ','ТРАНЗАКЦИИ','ДАННЫЕ','ЦЕНООБРАЗОВАНИЕ РИСКА'].map((x,i)=><div key={x} style={{transform:'rotate('+(i*45)+'deg) translateY(-150px) rotate('+(-i*45)+'deg)'}}>{x}</div>)}</div></Section>
<Section id="roadmap" eyebrow="08 / 12–24 МЕСЯЦЕВ" title="Строить через контрольные ворота, а не обещания." copy="Масштабирование следует за доказательством экономики. Каждая фаза должна заслужить переход к следующей."><div className="roadmap">{[['01','ФУНДАМЕНТ','0–3 МЕСЯЦЕВ','Доказать базовый поток и операционную модель.'],['02','ДИСТРИБУЦИЯ','3–6 МЕСЯЦЕВ','Соединить повторяемые клиентские пути эмитентов и инвесторов.'],['03','ЛИКВИДНОСТЬ','6–12 МЕСЯЦЕВ','Построить механизмы вторичного рынка и обратной связи по цене.'],['04','ПОВТОРНОЕ ИСПОЛЬЗОВАНИЕ','12–18 МЕСЯЦЕВ','Превратить ликвидность в финансирование и реинвестирование.'],['05','МАСШТАБИРОВАНИЕ','18–24 МЕСЯЦЕВ','Масштабировать только там, где доказана экономика contribution.']].map(([n,h,t,p])=><article key={n}><span>{n}</span><div><b>{h}</b><em>{t}</em><p>{p}</p></div></article>)}</div></Section>
<section className="final section"><div className="eyebrow">JASMINE / ФИНАЛЬНЫЙ ТЕЗИС</div><h2>Возможность не в том, чтобы выпускать больше цифровых активов.</h2><p>Возможность в том, чтобы сделать движение капитала более эффективным.</p><div className="final-flow">КАПИТАЛ <span>→</span> ДИСТРИБУЦИЯ <span>→</span> ЛИКВИДНОСТЬ <span>→</span> ПОВТОРНОЕ ИСПОЛЬЗОВАНИЕ <span>→</span> РОСТ</div></section><footer className="footer"><span>JASMINE / КАПИТАЛ ДИСТРИБУЦИЯ &amp; ЛИКВИДНОСТЬ КОНТУР</span><span>СТРАТЕГИЧЕСКАЯ КОНЦЕПЦИЯ / 2026</span></footer></main>}
